puts "hello World"
puts "hihihihihihi"
puts "hihihihihihia"
puts "hihihihihihib"
puts "hihihihihihib"
puts "hihihihihihic"
puts "hihihihihihid"
puts "hihihihihihia"
puts "hihihihihihib"
puts "hihihihihihic"
puts "hihihihihihid"
puts "hihihihihihie"
puts "hihihihihihia"
puts "hihihihihihib"
puts "hihihihihihid"
puts "hihihihihihie"
puts "hihihihihihi4"
